name: Deploy App
on:
  push:
    branches:
    - main

jobs:
  DeployDev:
    name: Build and Deploy to DEV
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1.5.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group
        uses: Azure/arm-deploy@v1.0.9
        with:
          template: ./iac/resourcegroup.bicep
          parameters: 'resourceGroupName=rg_cleanarchitecture_dev location=westeurope'
  
