name: Deploy Infra and App
on:
  push:
    branches:
    - main

jobs:
  DeployDev:
    name: Build and Deploy to DEV
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1.5.1
        with:
          client-id: ${{ secrets.AZURE_CREDENTIALS.clientId }}
          tenant-id: ${{ secrets.AZURE_CREDENTIALS.tenantId }}
          subscription-id: ${{ secrets.AZURE_CREDENTIALS.subscriptionId }}

      - name: Deploy Resource Group
        uses: Azure/arm-deploy@v1.0.9
        with:
          scope: subscription
          region: westeurope
          subscriptionId: '${{ secrets.AZURE_CREDENTIALS.subscriptionId }}'
          template: ./iac/resourcegroup.bicep
          parameters: 'resourceGroupName=rg_cleanarchitecture_dev location=westeurope'

      # - name: Deploy Azure Resources

      # - name: build, deploy, 
  
